site_name: async-python-sprint-2

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Главная: index.md
  - class Scheduler (Планировщик): scheduler.md
  - class Job (Задача): job.md
  - Тесты: tests.md
  - Как запускать этот проект: how-to-guides.md
  - Описание задания: README.md
  - mkdocs default index page: index-mkdocs.md
