site_name: async-python-sprint-2

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - search

nav:
  - Главная: index.md
  - Как запускать этот проект: how-to-guides.md
  - class Scheduler (Планировщик): scheduler.md
  - class Job (Задача): job.md
  - Тесты: tests.md
  - Дополнительно:
    - Про документатор mkdocs: mkdocs-basics.md
